### ISSUE TITLE
希望增加备份说明

### ISSUE THREAD

**Issue by aiwush** [hongyonghan/Docker_Microsoft365_E5_Renew_X#1]
增加用户信息配置文件位置说明，这样我可以在迁移docker的时候复制迁移

**Comment by hongyonghan** [comment]
您好！所有的配置文件都放在/app文件路径下，如果您以后有迁移的需要可以用命令将容器中/app路径下的文件复制出来。或者在一开始的时候就可以挂载数据卷到您的之前的全部文件中。如：
docker run -d -p 1066:1066 -v /root/Docker_Microsoft365_E5_Renew_X/Microsoft365_E5_Renew_X/:/app/ hanhongyong/ms365-e5-renew-x:latest
如此便可以实现您所要求的配置文件备份的功能，且您的容器中的文件和服务器主机中文件是一样的。

**Comment by aiwush** [comment]
> 

实际测试这样子docker是无法运行的

**Comment by hongyonghan** [comment]
您好！刚刚我实际测试了一下，是可以运行的，请问您报什么异常了呢？

**Comment by aiwush** [comment]
> 

我使用群辉运行会不断重启
