### ISSUE TITLE
能否增加/health接口以供监控运行状态

### ISSUE THREAD

**Issue by xiazeyu** [hongyonghan/Docker_Microsoft365_E5_Renew_X#11]
我使用了[uptime-kuma](https://github.com/louislam/uptime-kuma)来监控网站运行状态，但是他智能监控网站是否在线，无法监控账号是否运行正常。

之前一直报错TOKEN-HTTPER:The SSL connection could not be established, see inner exception.，但是由于我的服务器没有设置邮件提示，无法发现。

能否增加一个/health的API，当运行正常时返回{'status':'ok'}，不正常时返回{'status': 'fail', 'count': 1}

**Comment by hongyonghan** [comment]
最近科研任务繁忙，可能暂时不会进行修改了，过段时间会考虑将您的想法加到新版的镜像当中。

**Comment by hongyonghan** [comment]
你好，我增加了一个部署监控ms365的网站，目前用起来挺不错的，你也可以尝试一下

**Comment by xiazeyu** [comment]
您好，我之前就是用的自建uptimerobot，但是这个站它只能检测网站是否正常运行，无法检测是否正常续期。
所以提出了加一个api接口查看续期状况

**Comment by hongyonghan** [comment]
是的，这个网站只是能检测网站正常运行。但是我们也没有能力检测是否正常续期，这个网站也不过是模拟调用微软的api而已，我判断是否续签成功也都是通过在30天到期前是否收到短信来判断的。一般来说，只要开始的时候调用没有问题，后面调用也不会出问题，只要网站不掉线的话。我的网站目前稳定运行了接近10个月了。如果你还是不放心的话，可以在你的网站上添加多个账号，防止某一个账号突然出现异常而导致续签失败。

**Comment by xiazeyu** [comment]
这样啊...
我之前看网站上有状态提示的
应该是通过判断API是否成功执行来反馈的..这样的话感觉比单独检测网站会靠谱些

**Comment by hongyonghan** [comment]
上次调用统计： 16 | 16 | 0
今日调用统计： 374 | 373 | 1
上次调用统计： 6 | 6 | 0
今日调用统计： 433 | 433 | 0
这是我的两个账号的订阅，基本上每天都会执行吧。现在执行了基本会续订成功，但是后面被微软发现了这个漏洞可能也就无法使用这个方法来续签了，到那时即使都执行了也不一定能续期成功啊。这个就是不断调用api来尽量提高续签的成功率罢了。我看有的人不用这个网站续签，用桌面版只是一段时间调用一些api，也续签成功了，也没有必要太关注这个调用api的成功率啊。反正这个就是尽量不保存重要的材料就好。

**Comment by xiazeyu** [comment]
哦哦这样啊 我之前是因为组织策略加了2FA或者强制改密啥的 续约的账号0|0|433过一段时间... 然后就像有没有调用接口来检测状态啥的..

**Comment by hongyonghan** [comment]
后面会考虑增加一个功能，用来检测运行状态，如果运行状态有问题会发邮件通知。
