### ISSUE TITLE
关于无法保存数据

### ISSUE THREAD

**Issue by yan-forever** [hongyonghan/Docker_Microsoft365_E5_Renew_X#12]
在我添加完账号后reboot，再次开启服务，登录后发现一切被重置了

配置如下：

Archlinux

docker version：
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.18
 Git commit:        a224086349
 Built:             Thu Mar 24 08:56:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18
  Git commit:       87a90dc786
  Built:            Thu Mar 24 08:56:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.2
  GitCommit:        de8046a5501db9e0e478e1c10cbcfb21af4c6b2d.m
 runc:
  Version:          1.1.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

启动命令：docker run -d -p 1066:1066 -v /home/yanserver/Microsoft365_E5_Renew_X/Deploy:/Deploy  hanhongyong/ms365-e5-renew-x:latest
目录：
yanserver/
├── Desktop
├── Documents
├── Downloads
├── Microsoft365_E5_Renew_X
│   ├── Deploy
│   └── wwwroot
├── Music
├── Pictures
├── Public
├── Templates
└── Videos

**Comment by yan-forever** [comment]
安装时用的这个命令 docker pull hanhongyong/ms365-e5-renew-x:slim

**Comment by hongyonghan** [comment]
您好！首先，标签slim和latest是两个版本，如果您的设备资源有限，可以运行轻量化的版本slim，如果不是，可以使用latest版本，里面包含了更多可使用的软件。其次，正常来说不会因为重启而导致无法保存数据。对于这个问题，您可以通过命令`docker exec -it [容器ID] bash`进入容器查看/app/目录下是否有一个appdata文件夹，所有的数据都会保存在这个文件夹下。除此之外，您运行的命令可以有一些问题，因为Deploy目录是在/app目录下的。在数据卷时可以考虑将目录也映射到/app/Deploy目录下。如：`docker run -d -p 1066:1066 -v /home/yanserver/Microsoft365_E5_Renew_X/Deploy:/app/Deploy hanhongyong/ms365-e5-renew-x:latest`

**Comment by yan-forever** [comment]
> 您好！首先，标签slim和latest是两个版本，如果您的设备资源有限，可以运行轻量化的版本slim，如果不是，可以使用latest版本，里面包含了更多可使用的软件。其次，正常来说不会因为重启而导致无法保存数据。对于这个问题，您可以通过命令进入容器查看/app/目录下是否有一个appdata文件夹，所有的数据都会保存在这个文件夹下。除此之外，您运行的命令可以有一些问题，因为Deploy目录是在/app目录下的。在数据卷时可以考虑将目录也映射到/app/Deploy目录下。如：`docker exec -it [容器ID] bash``docker run -d -p 1066:1066 -v /home/yanserver/Microsoft365_E5_Renew_X/Deploy:/app/Deploy hanhongyong/ms365-e5-renew-x:latest`

谢谢您的回复

**我首先查看了目录**
root@af6b12b398fe:/app# cd Deploy/
root@af6b12b398fe:/app/Deploy# ls
Config.xml
root@af6b12b398fe:/app/Deploy# cd ..
root@af6b12b398fe:/app# cd appdata/
root@af6b12b398fe:/app/appdata# ls
DataBase
root@af6b12b398fe:/app/appdata# cd DataBase/
root@af6b12b398fe:/app/appdata/DataBase# ls
AspNetRoleClaims.csv  AspNetRoles.csv  AspNetUserClaims.csv  AspNetUserRoles.csv  AspNetUsers.csv  EXAccount.csv
EXAccountRun.csv

**然后我删除了原来的容器再次安装：**
[root@Yan-arch ~]# docker pull hanhongyong/ms365-e5-renew-x:latest
latest: Pulling from hanhongyong/ms365-e5-renew-x
Digest: sha256:f9c35c2a9d2ce09f254d7f25dd87b54a77b9214638a3da0d0eefffa0aad2e905
Status: Image is up to date for hanhongyong/ms365-e5-renew-x:latest
docker.io/hanhongyong/ms365-e5-renew-x:latest

**随后更换了启动命令为**docker run -d -p 1066:1066 -v /home/yanserver/Microsoft365_E5_Renew_X/Deploy:/app/Deploy hanhongyong/ms365-e5-renew-x:latest

**我将以下命令放进了sh脚本开机自启**
#!/bin/sh
systemctl start docker
docker run -d -p 1066:1066 -v /home/yanserver/Microsoft365_E5_Renew_X/Deploy:/app/Deploy hanhongyong/ms365-e5-renew-x:latest
**再次查看时仍然无法保存数据**
