### ISSUE TITLE
特赦时间能否修改的短一点

### ISSUE THREAD

**Issue by mizb** [hongyonghan/Docker_Microsoft365_E5_Renew_X#13]
有时候路由或者光猫重启，软件就会因为报错过多暂停账号。而自动特赦的时间为30天。。我就需要自己手动去执行特赦或者重启。一单因为网络原因报错后，能否改为1天后接着执行？

**Comment by hongyonghan** [comment]
您好！这个你可以根据您的需要自己去修改的。在Config.xml里面有<AutoSpecialPardonInterval>30</AutoSpecialPardonInterval>，可以尝试对这个进行修改，其他的原作者已经封装了，我无法修改。除此之外，可以尝试使用设定一定时间来执行容器重启命令来解决这个问题。

**Comment by exuan** [comment]
只能找原作者`The AutoSpecialPardonInterval value must be 30-999`

**Comment by hongyonghan** [comment]
嗯嗯，是的，最小是30。我的推荐是使用免费的容器平台来挂。

**Comment by hongyonghan** [comment]
可以参考部署文档中的Serverless部署的koyeb进行部署。
