### ISSUE TITLE
部署在koyeb等PaaS平台有个致命问题：云容器重启丢失所有数据

### ISSUE THREAD

**Issue by ChirmyRam** [hongyonghan/Docker_Microsoft365_E5_Renew_X#15]
类似于heroku等云容器平台，koyeb也会有重启实例的现象，不过heroku是每天强制重启，koyeb是隔几天重启一次。每次重启都会丢失实例在部署后的所有更改，恢复到初次部署时的状态，也就是会重新部署一次，造成数据丢失。我三天前部署在koyeb上面的实例，现在已被重启。

![image](https://user-images.githubusercontent.com/34760505/166476591-3a473939-a992-4bec-bf23-3543abf349d6.png)

其他支持部署在这些云平台的项目的解决办法就是站库分离，使用远端Mysql、postgreSQL储存数据，不过这对于RenewX显然是行不通的，差不多算是重构了。

所以koyeb目前只能算是临时搭建一下尝鲜使用，要不然隔几天就丢数据还真吃不消。

还有个不是办法的办法，提前构建一个已经配置好账号等数据的docker镜像，一旦部署就能跑起来，不过灵活性就没那么高了。

**Comment by hongyonghan** [comment]
目前推荐使用的平台是fly，这个是不自动重启的。最好还是自己有一个服务器啊。免费的服务器现在有甲骨文和微软云等等。

**Comment by ChirmyRam** [comment]
> 目前推荐使用的平台是fly，这个是不自动重启的。最好还是自己有一个服务器啊。免费的服务器现在有甲骨文和微软云等等。

很遗憾flyio也是会过一段时间就会重启的🤐，可能每月重启一两次，很少有不重启的云容器平台，我玩过好多个平台，不会重启的只见过railway，不过railway现在风控变得贼严。我当然是有自己的服务器，我提这个的目的是建议在云平台部署方式里面提醒一下有丢数据的风险。

**Comment by vikim540** [comment]
我看别人好的办法就是 用 sqlite 备份到GitHub， 然后重启的时候 在拉取下备份数据库就ok，  可以放一些不重要的东西

**Comment by ChirmyRam** [comment]
如何用sqlite备份？本程序的数据库不是sqlite。
