### ISSUE TITLE
Docker部署希望支持ARMV8架构的机器

### ISSUE THREAD

**Issue by 771695775** [hongyonghan/Docker_Microsoft365_E5_Renew_X#16]
比如R2S R4S 斐讯N1这种ARMV8架构机器的Docker

**Comment by hongyonghan** [comment]
您好！我之前增加了arm版本的docker，您可以尝试一下是否可以运行。命令如下：`docker run -d -p 1066:1066 hanhongyong/ms365-e5-renew-x:arm`。有问题，可以继续给我反馈。

**Comment by 771695775** [comment]
> 您好！我在添加arm版本的docker之前，您可以试一下是否可以运行。命令如下：`docker run -d -p 1066:1066 hanhongyong/ms365-e5-renew-x:arm`。有问题，可以继续给我反馈。

非常感谢，确实可以使用了，但是为什么时间显示的是错误的？现在是下午15.30，网站显示的是7点，虽然不影响使用
![QQ截图20220508152702](https://user-images.githubusercontent.com/63600136/167286323-ff15665d-0932-4946-a273-e181bdc86cd3.png)

**Comment by hongyonghan** [comment]
对，这个还是之前的编译的版本，没有修改时区，差八个小时，后期有时间会在编译新的版本吧。

**Comment by hongyonghan** [comment]
我记得那个版本好像是配置了时区，时间有点久忘记了。。。。您可以尝试命令，看看时间是不是正常的啊。`docker run -d -p 1066:1066 -e TZ=Asia/Shanghai --name ms365  hanhongyong/ms365-e5-renew-x:arm`

**Comment by 771695775** [comment]
> 

用这个命令重新部署以后完美解决，非常感谢！
