### ISSUE TITLE
大佬 有没有可能支持远程数据库

### ISSUE THREAD

**Issue by decadeicey** [hongyonghan/Docker_Microsoft365_E5_Renew_X#18]
koyeb之类的重启实例会清数据 把配置信息之类的保存在远程数据库里是不是就可以了

**Comment by hongyonghan** [comment]
这个暂时不行啊，我是在作者SundayRX上做的容器部署服务，SundayRX目前只给了读取文件的服务啊。我推荐的是自己购买云服务器去部署这个服务啊
