### ISSUE TITLE
配置文件启用站点共享时，缺少https证书无法运行

### ISSUE THREAD

**Issue by 2826915729** [hongyonghan/Docker_Microsoft365_E5_Renew_X#2]
![image](https://user-images.githubusercontent.com/31442507/155893297-05e8e5af-2da9-4634-bcee-565e779d1963.png)

**Comment by hongyonghan** [comment]
你好！这里只是提供基本的容器的部署。证书相关的操作还需要你自己去配置，可以参考这个教程：https://blog.csdn.net/qq_33212020/article/details/119747634

**Comment by 2826915729** [comment]
我使用的是方式2配置https证书：
服务程序Kestrel—(HTTPS localhost)—Nginx/IIS/Apache—(HTTPS 外部访问域名)—外部Internet
反向代理服务器部分请自行配置

执行下列两个命令 以创建localhsot HTTPS证书 该证书时效为1年

```
dotnet dev-certs https --clean
dotnet dev-certs https
```

Configuration.HTTPS.Enable设置为true
Configuration.HTTPS.Certificate设置为空（什么都不要填）
Configuration.HTTPS.Password设置为空（什么都不要填）

```
dotnet dev-certs https --clean
dotnet dev-certs https
```
缺少这两步所以无法运行

**Comment by hongyonghan** [comment]
使用docker exec命令进入容器内部，来执行上述命令可以实现，您可以尝试一下。

**Comment by 2826915729** [comment]
> 

`docker exec` 需要正常运行才能进入容器，因为容器一直在重启，无法进入

**Comment by hongyonghan** [comment]
非常抱歉，我会在两天内更新最新的镜像，将证书的问题尝试进行解决。
