### ISSUE TITLE
非登录调用有失败的调用

### ISSUE THREAD

**Issue by poctopus** [hongyonghan/Docker_Microsoft365_E5_Renew_X#21]
按照配置说明，增加了11个相关API的权限
Calendars.Read;Contacts.Read;Directory.Read.All;Files.Read.All;Files.ReadWrite.All;Mail.Read;Mail.Send;MailboxSettings.Read;Notes.Read.All;Sites.Read.All;User.Read.All;
![image](https://user-images.githubusercontent.com/9878354/187327911-ef5b9f06-8564-4b5d-aaca-dc53dbea4cec.png)

但是在后台看到有3个API还是有100%报错，不知道是哪里配置错误了。
用户.见解.列出趋势
网站和列表.网站.关注网站列表
人员和工作场所智能.见解.列出趋势
![image](https://user-images.githubusercontent.com/9878354/187328022-12d5ae9d-2b7a-4596-a545-eeafee14951b.png)

**Comment by hongyonghan** [comment]
尝试用别的账号试试呢？或者用管理员的账号试试？我的也有一些api调用错误，但是目前来看不影响正常续期使用？

**Comment by poctopus** [comment]
用的就是管理员的账号登录，比较奇怪。

**Comment by hongyonghan** [comment]
续订异常了吗？
