### ISSUE TITLE
Change Admin account password

### ISSUE THREAD

**Issue by tuthanika** [hongyonghan/Docker_Microsoft365_E5_Renew_X#25]
Can you help me how to change admin account password on koyeb? I used koyeb's Console with command vim Config.xml but it doesn't show up as your instructions.

**Comment by hongyonghan** [comment]
Do you have screenshots of the operation?

**Comment by tuthanika** [comment]
> Do you have screenshots of the operation?
![1](https://user-images.githubusercontent.com/22352264/209480554-1555c762-bd01-46f5-83c1-337fe231291f.png)
![2](https://user-images.githubusercontent.com/22352264/209480555-e5b42660-7462-45c7-9b4d-a495daa79258.png)
![3](https://user-images.githubusercontent.com/22352264/209480556-59676119-1bea-43c2-b831-a9ab5bafb86b.png)
![4](https://user-images.githubusercontent.com/22352264/209480557-e23cb560-a39d-4cca-9372-641320f1689d.png)
![5](https://user-images.githubusercontent.com/22352264/209480558-7059a3d3-cbde-4aca-9a45-d30e49147a29.png)
![6](https://user-images.githubusercontent.com/22352264/209480559-0c50d8de-82da-4896-9d6f-19f75ec963d4.png)
![7](https://user-images.githubusercontent.com/22352264/209480560-cf6f3b83-85f3-40b0-87c8-51681bbde86c.png)

**Comment by hongyonghan** [comment]
Getting the information from the screenshot, the Config.xml is not found at the location of "/app/Config.xml".
The reason why the password can not be changed is that the container is running.
1.get the Config.xml from the [link](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/tree/main/Microsoft365_E5_Renew_X/Deploy)
2.create the Config.xml file in the koyeb and change the password.
3. excute the code: `docker run -d -p 1066:1066 -v /root/Deploy/Config.xml:/app/Deploy/Config.xml  hanhongyong/ms365-e5-renew-x:latest`

**Comment by tuthanika** [comment]
I followed the instructions, but password didn't change. /root/Deploy/Config.xml and /app/Deploy/Config.xml
both exist and contain the imported configuration.

**Comment by hongyonghan** [comment]
please notice the warning!!!
![image](https://user-images.githubusercontent.com/53131561/209531307-e069cbf7-fcde-4fcc-a1ad-222fdd226e22.png)
the warning may be remind you that you have opened this file but did not close this file and a cache file was generated.
you need to delete the container and try to change the password. 
Of course, you can modify the password in Config.xml according to the dockerfile file and create your own separate container, so you don't need to modify the password directly. 
In fact, as long as you modify the mapped port to ensure that your domain name is not leaked, it is safe enough to not modify the login password

**Comment by tuthanika** [comment]
I deleted the .swp file and redeployed it to clean edit, but the result is still the same. Maybe I need to learn how to build my own dockerfile.

**Comment by hongyonghan** [comment]
ok
