### ISSUE TITLE
隔几天就会因为api调用失败过多暂停，

### ISSUE THREAD

**Issue by ershouqingge** [hongyonghan/Docker_Microsoft365_E5_Renew_X#26]
![LMSDK XT_SNL63{2ISK6$SV](https://user-images.githubusercontent.com/96559099/212041191-44953998-0a2c-4659-acf1-e9b7c06164cd.png)

**Comment by hongyonghan** [comment]
你好，这个api调用失败过多暂停是和你的账号有关系的。账号暂停了，但是容器不会停止运行。建议你首先查一下是否权限给全部授权了。其次，可以添加多个账号到你的网站下面。第三，调用方式尽量选择登录调用。调用方式： 登录调用
下面是我部署的网站的记录：
账号1：
当前状态： 正在运行
调用方式： 登录调用
创建时间： 07/31/2022 03:17:26
上次调用时间： 01/12/2023 12:46:37
上次调用统计： 10 | 10 | 0
下次调用时间： 01/12/2023 13:07:11
今日调用统计： 600 | 599 | 1
账号2：
当前状态： 正在运行
调用方式： 登录调用
创建时间： 11/25/2022 02:38:51
上次调用时间： 01/12/2023 12:47:26
上次调用统计： 4 | 4 | 0
下次调用时间： 01/12/2023 13:14:00
今日调用统计： 551 | 551 | 0

**Comment by ershouqingge** [comment]
> 
我就是用的登录调用的，权限也检查过了，添加了多个账号目前情况还是一样。  是否可能是网络的问题呢，我在环境变量添加http_proxy参数是否可以代理呢。

**Comment by hongyonghan** [comment]
可以试试使用http_proxy参数。但是我没有试过这个。或者你试试删除以前的镜像，再重新运行一下呢？
