### ISSUE TITLE
docker启动不起来

### ISSUE THREAD

**Issue by 0MM592** [hongyonghan/Docker_Microsoft365_E5_Renew_X#27]
你好
docker run -d -p 1066:1066  hanhongyong/ms365-e5-renew-x:latest
启动不了容器
这是log
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:36.218931443Z"}
{"log":"      Application is shutting down...\n","stream":"stdout","time":"2023-01-26T08:39:36.218987023Z"}
{"log":"\u001b[40m\u001b[1m\u001b[33mwarn\u001b[39m\u001b[22m\u001b[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]\n","stream":"stdout","time":"2023-01-26T08:39:36.293889113Z"}
{"log":"      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.\n","stream":"stdout","time":"2023-01-26T08:39:36.294025437Z"}
{"log":"\u001b[40m\u001b[1m\u001b[33mwarn\u001b[39m\u001b[22m\u001b[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]\n","stream":"stdout","time":"2023-01-26T08:39:36.408418543Z"}
{"log":"      No XML encryptor configured. Key {bc329cf5-a681-461f-9283-f91ab4cbde2e} may be persisted to storage in unencrypted form.\n","stream":"stdout","time":"2023-01-26T08:39:36.408467944Z"}
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:41.292160432Z"}
{"log":"      Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.\n","stream":"stdout","time":"2023-01-26T08:39:41.292204559Z"}
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:41.910594777Z"}
{"log":"      Now listening on: http://[::]:1066\n","stream":"stdout","time":"2023-01-26T08:39:41.910646512Z"}
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:41.911127603Z"}
{"log":"      Application started. Press Ctrl+C to shut down.\n","stream":"stdout","time":"2023-01-26T08:39:41.911144358Z"}
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:41.911344887Z"}
{"log":"      Hosting environment: Production\n","stream":"stdout","time":"2023-01-26T08:39:41.911359791Z"}
{"log":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n","stream":"stdout","time":"2023-01-26T08:39:41.911556696Z"}
{"log":"      Content root path: /app\n","stream":"stdout","time":"2023-01-26T08:39:41.911571321Z"}

**Comment by 0MM592** [comment]
vps是ipv6的，和这个是不是有关系

**Comment by hongyonghan** [comment]
是不是vps的机器的不是amd的？

**Comment by underlaw** [comment]
用arm版，作者的第一个arm的用不了

**Comment by hongyonghan** [comment]
hanhongyong/ms365-e5-renew-x:arm64v8
试试这个？
