### ISSUE TITLE
docker在映射/app目录后无法正常启动

### ISSUE THREAD

**Issue by aiwush** [hongyonghan/Docker_Microsoft365_E5_Renew_X#3]
日志显示如下：
root@WushNAS:~# docker logs hanhongyong-ms365-e5-renew-x
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by hongyonghan** [comment]
您好！从日志上来看，是您所用的平台没有.net,可以尝试一下命令解决问题：
CentOS 8
sudo dnf install dotnet-sdk-3.1
CentOS 7
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
sudo yum install dotnet-sdk-3.1
————————————————
版权声明：本文为CSDN博主「SundayRX」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_33212020/article/details/119747634

**Comment by hongyonghan** [comment]
您好！我已经更新了最新的镜像，解决了这个问题，欢迎试用！

**Comment by aiwush** [comment]
> 您好！我已经更新了最新的镜像，解决了这个问题，欢迎试用！

.net的迁移大概有点问题。会出现报错：

**Comment by aiwush** [comment]
> 您好！我已经更新了最新的镜像，解决了这个问题，欢迎试用！

dotnet ef工具可能存在问题

**Comment by hongyonghan** [comment]
对之前的镜像进行了修改，现在还有问题吗？

**Comment by aiwush** [comment]
> 对之前的镜像进行了修改，现在还有问题吗？

试了下还是存在那个问题

**Comment by aiwush** [comment]
> 

![image](https://user-images.githubusercontent.com/98788152/156533918-166cda8f-99e5-4abf-87d8-66b407c46542.png)
![image](https://user-images.githubusercontent.com/98788152/156533959-95a28b48-a118-44c8-b699-1d9e1fe67d6a.png)
![image](https://user-images.githubusercontent.com/98788152/156534002-915f20c8-5543-426f-b976-c413d69b2266.png)

**Comment by hongyonghan** [comment]
您好！很抱歉不能解决您的问题，我部署了几次没有出现您说过的问题，可能是我的设备不是群晖设备。我的建议是您进入容器后将您需要的配置或者文件复制进去，然后重新启动设备进行尝试。

**Comment by skyshenma** [comment]
记得把大佬的github上的/Deploy文件放进你的群晖的docker/e5renewx//Deploy里面去，里面就只有一个Config.xml文件，及docker/e5renewx//Deploy/Config.xml

**Comment by hongyonghan** [comment]
可以按照上面的同学的回答试一下。 @aiwush ，一般来说，容器是没有问题的，更多的可能是配置的问题或者数据卷的问题。

**Comment by aiwush** [comment]
感谢建议，我将会尝试一下

**Comment by lonzoen** [comment]
遇到同样问题，映射/deploy后正常
