### ISSUE TITLE
大佬，docker运行问题

### ISSUE THREAD

**Issue by underlaw** [hongyonghan/Docker_Microsoft365_E5_Renew_X#31]
![image](https://user-images.githubusercontent.com/33020405/216816909-fe956ee4-c825-46e2-93ae-106624b48b46.png)

用的openwrt里的docker，api调用17个权限，出错的不少。最后自己停止了

**Comment by hongyonghan** [comment]
是不是你账户的权限问题,这些api的权限都开放了嘛？然后再检查一下添加账户的时候选择了是否为登录调用方式？当调用错误过多就自动停止了，这是我的一个账户的情况。
上次调用统计： 21 | 21 | 0

下次调用时间： 02/05/2023 12:09:20

今日调用统计： 603 | 603 | 0

**Comment by underlaw** [comment]
都按教程开放了哦，也是登录方式调用的。有时候全行，有时候又出错。好像随机一样

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216817442-b91ea5bd-d95d-4afc-919b-026eb8cc4d9a.png)
手动编辑下，保存，刚运行又全调用到了

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216817514-c83d3860-f53d-4fa0-a84d-317577844d1d.png)
现在正确 错误对半开吧

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216817737-899c1be3-ccdf-4546-a901-aff05e39a1aa.png)
用的子账号，继承过来的权限

**Comment by hongyonghan** [comment]
稍等，我开一个账号，你去测试一下，看在我部署的账号上是否可以运行成功。

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216818563-2de6d623-0e85-47e9-910f-208d579a562b.png)
这次也只调用到了一部分

**Comment by underlaw** [comment]
> 稍等，我开一个账号，你去测试一下，看在我部署的账号上是否可以运行成功。

等你

**Comment by hongyonghan** [comment]
好了，我用我自己的服务器搭建了一个服务，地址和密码放在readme主页上了，你放你的账号到上面然后测试一下吧。看看是不是你的网络问题还是账号的问题。

**Comment by underlaw** [comment]
可我不知道你的网站地址哦

**Comment by underlaw** [comment]
https://[e5.sundayrx.net](https://e5.sundayrx.net/)/ 这个不行

**Comment by hongyonghan** [comment]
不不不，就是github这个项目的readme文件的部署步骤下面

**Comment by underlaw** [comment]
收到

**Comment by underlaw** [comment]
> 不不不，就是github这个项目的readme文件的部署步骤下面

https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/issues/31#issuecomment-1417718919

**Comment by underlaw** [comment]
https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/issues/31#issuecomment-1417718919

**Comment by underlaw** [comment]
stdout: [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
stdout:       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
stdout: [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
stdout:       No XML encryptor configured. Key {109aee77-7ae2-4e9f-bd02-17cbbefea808} may be persisted to storage in unencrypted form.
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Now listening on: http://[::]:1066
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Application started. Press Ctrl+C to shut down.
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Hosting environment: Production
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Content root path: /app
stdout: [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
stdout:       An exception was thrown while deserializing the token.
stdout: Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
stdout:  ---> System.Security.Cryptography.CryptographicException: The key {1ff46abf-a560-4fd6-9822-cd0279be93cd} was not found in the key ring.
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
stdout:    --- End of inner exception stack trace ---
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Application is shutting down...
stdout: [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
stdout:       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Now listening on: http://[::]:1066
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Application started. Press Ctrl+C to shut down.
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Hosting environment: Production
stdout: [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
stdout:       Content root path: /app
stdout: [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
stdout:       An exception was thrown while deserializing the token.
stdout: Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
stdout:  ---> System.Security.Cryptography.CryptographicException: The key {1ff46abf-a560-4fd6-9822-cd0279be93cd} was not found in the key ring.
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
stdout:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
stdout:    --- End of inner exception stack trace ---
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
stdout:    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)


这是窗口log

**Comment by hongyonghan** [comment]
http://hanhongyong.eu.org:1066/Admin/Login?ReturnUrl=%2F

**Comment by hongyonghan** [comment]
我这可以访问啊

**Comment by underlaw** [comment]
***@***.***

这是按教程里的16个权限，这是管理员账号设置的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: hanhongyong ***@***.***>
发送时间: Sunday, February 5, 2023 7:53:31 PM
收件人: hongyonghan/Docker_Microsoft365_E5_Renew_X ***@***.***>
抄送: underlaw ***@***.***>; Author ***@***.***>
主题: Re: [hongyonghan/Docker_Microsoft365_E5_Renew_X] 大佬，docker运行问题 (Issue #31)


是不是你账户的权限问题,这些api的权限都开放了嘛？然后再检查一下添加账户的时候选择了是否为登录调用方式？当调用错误过多就自动停止了，这是我的一个账户的情况。
上次调用统计： 21 | 21 | 0

下次调用时间： 02/05/2023 12:09:20

今日调用统计： 603 | 603 | 0

―

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216823271-8884a95a-a916-435d-8fb1-2b0d96e2584a.png)

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216823383-e414ce8d-54f8-4296-ac56-d2bb05f3eb3b.png)
权限应该没问题，用桌面版如上图
![image](https://user-images.githubusercontent.com/33020405/216823445-8796a320-81f5-47ef-b8d0-8e5d51d4a4b2.png)

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216823708-d6d820a9-b5fc-47c7-a2b0-7ec10398d6df.png)

子账号就会出现，出错多了暂停。是不是因为只授权了17个的原因了

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/216824354-cdde4f22-1bbb-4878-9732-836be42743ed.png)
别外这docker调用api的数量是随机的吗。  主账号没出错，但这每次个数都不一样

**Comment by underlaw** [comment]
> 调用随机的，我也有子账号，子账号也没有问题。你看看主账号给子账号的权限是不是管理员权限啊？一般是管理员权限就没问题啊

那主账号是正常的了，我去看看子账号怎么给管理员权限

**Comment by underlaw** [comment]
> 调用随机的，我也有子账号，子账号也没有问题。你看看主账号给子账号的权限是不是管理员权限啊？一般是管理员权限就没问题啊

![image](https://user-images.githubusercontent.com/33020405/216880281-dbf018ee-dd4a-44d0-9bec-dc93db843011.png)
设这个就可以吗

**Comment by hongyonghan** [comment]
也可以。你试试啊

**Comment by underlaw** [comment]
> 也可以。你试试啊

![image](https://user-images.githubusercontent.com/33020405/216903768-b80731fa-dc4e-453b-a425-98066febb0d6.png)
折腾好了，在注册应该里面有个“组”，把这子账号加进“应用程序”中的“组”里，就可以了
