### ISSUE TITLE
配置完成後運行失敗

### ISSUE THREAD

**Issue by kurokawaikki** [hongyonghan/Docker_Microsoft365_E5_Renew_X#32]
您好，
我配置完成後，但是運行之後出現大量失敗。
出現的錯誤如下:

个人联系人.类别.列出类别
TOKEN-HTTPER:Resource temporarily unavailable
失败
日历.日历.列出日历
TOKEN-HTTPER:Resource temporarily unavailable
失败
用户.见解.共享的列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
人员和工作场所智能.见解.共享的列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
用户.用户设置.获取设置
TOKEN-HTTPER:Resource temporarily unavailable
失败
人员和工作场所智能.见解.列出趋势
TOKEN-HTTPER:Resource temporarily unavailable
失败
邮件.邮件文件夹.列出邮件文件夹
TOKEN-HTTPER:Resource temporarily unavailable
失败
文件.驱动器.列出子项
TOKEN-HTTPER:Resource temporarily unavailable
失败
人员和工作场所智能.见解.使用的列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
用户.用户.列出用户
TOKEN-HTTPER:Resource temporarily unavailable
失败
用户.见解.使用的列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
客户预订(预览版).预订货币.列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
文件.驱动器项目.上载
TOKEN-HTTPER:Resource temporarily unavailable
失败
组.组.列出组
TOKEN-HTTPER:Resource temporarily unavailable
失败
日历.日历组.列出日历组
TOKEN-HTTPER:Resource temporarily unavailable
失败
网站和列表.网站.关注网站列表
TOKEN-HTTPER:Resource temporarily unavailable
失败
邮件.规则.列出规则
TOKEN-HTTPER:Resource temporarily unavailable
失败
个人联系人.联系人.列出联系人
TOKEN-HTTPER:Resource temporarily unavailable
失败

非常感謝您!

**Comment by hongyonghan** [comment]
api权限问题,检查权限

**Comment by kurokawaikki** [comment]
我覺得應該不是API問題。
因為同樣的授權，如果使用桌面版本的MS365 Renew plus就可以正常運行。
可以請教一下要如何debug呢?
非常感謝。

**Comment by chpamhe** [comment]
DOCKER 中会经常出现，桌面版本的就不会（或者说概率小）。桌面端没尝试过一直开着电脑挂着·····
