### ISSUE TITLE
docker版本不知道在哪一键获取API权限

### ISSUE THREAD

**Issue by cuiyanjie** [hongyonghan/Docker_Microsoft365_E5_Renew_X#33]
使用过windwos客户端版本，在添加账号的时候有个一键自动管理API授权按钮，可以代表组织授权API权限。在docker版的网页版里没找到类似的操作

**Comment by hongyonghan** [comment]
docker的网站有个连接可以找到，在主页快速链接，Azure主页可以找到。https://portal.azure.com/#home
