### ISSUE TITLE
docker运行最近无缘无故出问题

### ISSUE THREAD

**Issue by underlaw** [hongyonghan/Docker_Microsoft365_E5_Renew_X#36]
#31    这是我折腾好了的。但今天一看出问题了

![image](https://user-images.githubusercontent.com/33020405/221852856-f99a71c7-1c18-4607-bdec-ba775acd1251.png)

**Comment by hongyonghan** [comment]
这和个人机器的网络相关，建议部署在腾讯云或者阿里云等服务器上面，然后尽量一个docker镜像部署一个账号即可。我自己的账号部署了一年了也没有运行停止。还有一个问题是最近太多人使用这种方式去进行访问，这也造成了访问服务的堵塞。后面会抽时间增加一个运行状态的检测，如果机器有异常会发邮件通知。
