### ISSUE TITLE
调用api报错

### ISSUE THREAD

**Issue by guoluyuan** [hongyonghan/Docker_Microsoft365_E5_Renew_X#39]
当前状态： 已暂停 (错误率过高-可能由应用程序缺少权限、新账号未初始化完成、Microsoft网络波动等因素造成)
调用方式： 登录调用
创建时间： 03/11/2023 10:26:25
上次调用时间： 03/11/2023 10:31:25
上次调用统计： 10 | 0 | 10
下次调用时间： NA
今日调用统计： 10 | 0 | 10
正常按照教程来的，但是就是报错，不知道咋回事，

**Comment by hongyonghan** [comment]
是一开始就报错吗？如果是保存以后一开始就报错，一般的原因是应用程序缺少权限，建议去核对博客上的要求的权限是否都给了。

**Comment by guoluyuan** [comment]
一开始就报错，对着权限表试了好几次了都是这样，博客上面写的权限都给了的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月11日(周六) 中午12:47
收件人: ***@***.***&gt;;
抄送: "Guo ***@***.******@***.***&gt;;
主题: Re: [hongyonghan/Docker_Microsoft365_E5_Renew_X] 调用api报错 (Issue #39)




 
是一开始就报错吗？如果是保存以后一开始就报错，一般的原因是应用程序缺少权限，建议去核对博客上的要求的权限是否都给了。

**Comment by hongyonghan** [comment]
建议再核对一下权限，看看博客的其他文章，尤其注意是否是登录的权限，前面出现这个问题基本是权限的问题。
如果权限审查完还是有问题，建议换个机器运行docker容器，排除一下是不是由网络问题引起的。

**Comment by underlaw** [comment]
我也反馈过这个问题，运行一段时间后，就会出现这个。也不会自动重启继续。

**Comment by hongyonghan** [comment]
我检查了可能发生这个问题的原因。主要是一下几个方面造成的。（1）一个ip上绑定了太多的账号，导致了并发数目太多。这里的建议是尽量保证一个ip上账号数目不要超过3个，然后尽量使用自己购买的云服务器，免费的服务大家都在用可能会出问题。（2）由于网络引起的问题。国内的服务器或者网络容易在凌晨容易出现问题，如果有国外的vps机器，推荐安装到国外的机器上。

**Comment by hongyonghan** [comment]
我检查了可能发生这个问题的原因。主要是一下几个方面造成的。（1）一个ip上绑定了太多的账号，导致了并发数目太多。这里的建议是尽量保证一个ip上账号数目不要超过3个，然后尽量使用自己购买的云服务器，免费的服务大家都在用可能会出问题。（2）由于网络引起的问题。国内的服务器或者网络容易在凌晨容易出现问题，如果有国外的vps机器，推荐安装到国外的机器上。

**Comment by underlaw** [comment]
> 我检查了可能发生这个问题的原因。主要是一下几个方面造成的。（1）一个ip上绑定了太多的账号，导致了并发数目太多。这里的建议是尽量保证一个ip上账号数目不要超过3个，然后尽量使用自己购买的云服务器，免费的服务大家都在用可能会出问题。（2）由于网络引起的问题。国内的服务器或者网络容易在凌晨容易出现问题，如果有国外的vps机器，推荐安装到国外的机器上。

安装 在自己的openwrt 上的。
