### ISSUE TITLE
这个不支持arm框架吗

### ISSUE THREAD

**Issue by lll-999** [hongyonghan/Docker_Microsoft365_E5_Renew_X#4]
arm无法启动容器

**Comment by hongyonghan** [comment]
您好！我刚刚新增加了支持arm的镜像，但是我身边没有arm的设备，无法进行测试。如果可以，麻烦您测试一下arm的容器是否可以正常使用。镜像的名字为hanhongyong/ms365-e5-renew-x:arm.
`docker run -d -p 1066:1066  hanhongyong/ms365-e5-renew-x:arm`
更加详细的配置方法可以参照latest版本的相关内容，只需要将latest替换为arm即可。如果可以使用，请告知于我，谢谢！

**Comment by lll-999** [comment]
还是提示standard_init_linux.go:228: exec user process caused: exec format error，我没有描述清楚，是arm64/v8

**Comment by hongyonghan** [comment]
难怪，我之前镜像是arm32的，现在更新了arm64v8的镜像，麻烦测试一下是否可用？

**Comment by lll-999** [comment]
貌似没有变化，一样无法运行

**Comment by hongyonghan** [comment]
我查找了相关资料，得到可能原因是针对arm设备需要指定`--platform linux/arm64`，麻烦您现在测试一下是否可以使用？

**Comment by hongyonghan** [comment]
我在build的时候已经指定了，您只需要在尝试一下看能否运行即可。

**Comment by lll-999** [comment]
还是一样哈，我已经重新拉取镜像了

**Comment by lll-999** [comment]
是的，一样的错误

**Comment by hongyonghan** [comment]
我尝试修改了两个镜像，tag分别为arm64v8和arm，你可以分别尝试一下。如果有问题，再联系我。

**Comment by lll-999** [comment]
两个镜像都已经尝试过了，还是没法运行

**Comment by hongyonghan** [comment]
我重新使用docker buildx ``编译了一下镜像，您看看是否可以使用，`hanhongyong/ms365-e5-renew-x:arm`
如果还是不行的话，使用docker` logs命令查看一下容器的日志，然后将日志复制出来发给我。

**Comment by lll-999** [comment]
[root@localhost Microsoft365_E5_Renew_X]# docker run -d -p 1066:1066 hanhongyong/ms365-e5-renew-x:arm
5a9dd40e22a4cf0897e97d91d914d34120eecef660cdcb44100bb9ef0dc66643
[root@localhost Microsoft365_E5_Renew_X]#这是创建容器的时候，这一次镜像没有提示amd64，不兼容之类的了

**Comment by lll-999** [comment]
[root@localhost ~]# docker logs laughing_boyd
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error   这个是创建容器后启动失败的日志

**Comment by hongyonghan** [comment]
应该是基础镜像不兼容的问题，我重新修改了基础镜像，你看一下可以使用吗

**Comment by lll-999** [comment]
还是不行哈

**Comment by hongyonghan** [comment]
您好！sdk和aspnet都换成了arm的镜像了，您再尝试一下！

**Comment by lll-999** [comment]
![SmartSelect_20220309-231632_JuiceSSH](https://user-images.githubusercontent.com/72665660/157471163-f441f8c5-2486-4bbf-bf7e-a85a8f95dff6.jpg)
![SmartSelect_20220309-231507_Kiwi Browser](https://user-images.githubusercontent.com/72665660/157471180-0f38bfcc-0ad6-48db-8045-30f4154f8242.jpg)
👍现在可以正常运行了，arm64环境下

**Comment by hongyonghan** [comment]
好的好的，那我就把arm架构的镜像加进去了，麻烦您对镜像进行测试了！

**Comment by lll-999** [comment]
客气了，应该谢谢你们这些大佬适配才是😅
