### ISSUE TITLE
请问docker版的API调用频率怎么设置

### ISSUE THREAD

**Issue by JohnnyCjy** [hongyonghan/Docker_Microsoft365_E5_Renew_X#40]
PC端的E5 Renew Plus可以适度降低调用频率选择实验性设置（实验性设置模拟865工作制） ，像docker这样的一般都是24小时运行，如果一天到晚调用API，是否就不是那么像开发者。

**Comment by hongyonghan** [comment]
目前不可以设置频率啊。目前这个频率也不高啊。

**Comment by Do1e** [comment]
> PC端的E5 Renew Plus可以适度降低调用频率选择实验性设置（实验性设置模拟865工作制） ，像docker这样的一般都是24小时运行，如果一天到晚调用API，是否就不是那么像开发者。

可以在crontab里加docker stop和docker start，曲线救国
