### ISSUE TITLE
大神，几个建议，希望改进

### ISSUE THREAD

**Issue by underlaw** [hongyonghan/Docker_Microsoft365_E5_Renew_X#41]
api调用时不时会出错，出错后不会重启，就会僵死在那。（和你交流过几次，布置是没有问题的，权限都正确）

希望改进一下，增加出错后能邮件通知什么的，或出错后暂停多少小时再自动重启任务。api频率虽然是随机的，但有时候随机数会很大，是否把这最大随机数调小一点。

个人openwrt 的docker 布置。

**Comment by hongyonghan** [comment]
目前已经做好了邮件通知版本的docker镜像，还在内测当中，等内测没有问题的话会第一时间发布。

**Comment by OwnerCM** [comment]
> 目前已经做好了邮件通知版本的docker镜像，还在内测当中，等内测没有问题的话会第一时间发布。

大佬，邮件通知版本的docker镜像希望也能支持arm，谢谢！

**Comment by underlaw** [comment]
> 目前已经做好了邮件通知版本的docker镜像，还在内测当中，等内测没有问题的话会第一时间发布。

重启 运行，和频率调整支持吗

**Comment by Wyatt323** [comment]
刚想发个邮件通知的issue，正好看到，期待

**Comment by hongyonghan** [comment]
目前只考虑了邮件通知，关于频率和重启会在下一个版本考虑。

**Comment by Wyatt323** [comment]
光有邮件其实也够了，目前3个月使用下来还是比较稳定。就刚搭建的时候出现账号停用的情况比较频繁，现在已经稳定了，但总会时不时来一下。
话说出现账号停用是因为网络波动吗，我目前搭建在本地，如果是网络波动的问题我就迁到vps上了

**Comment by underlaw** [comment]
> 目前只考虑了邮件通知，关于频率和重启会在下一个版本考虑。

ARM64版，是用更新命令更新吗，还是全新安装了？大神

**Comment by hongyonghan** [comment]
arm64版本的镜像正在重新制作，近期会上线。

**Comment by hongyonghan** [comment]
arm64v8版本已经开放，欢迎试用。
