### ISSUE TITLE
网页打不开了

### ISSUE THREAD

**Issue by a1564471347** [hongyonghan/Docker_Microsoft365_E5_Renew_X#47]
今天突然监控网页打不开了，ip加1066端口

**Comment by hongyonghan** [comment]
看一下镜像的日志，docker logs 容器ID。是最近更新了镜像吗？

**Comment by a1564471347** [comment]
这个logs命令查询没有

**Comment by a1564471347** [comment]
邮件那个安装命令可以了，其他所有命令都可以删了根本打不开包括arm专属命令和latest命令

**Comment by hongyonghan** [comment]
现在用的主要是部署里面那个和arm64v8这俩，但是arm64v8还没有反馈到底可不可以用。

**Comment by a1564471347** [comment]
邮件通知推荐下那个可以用，arm64镜像专属现在不能用了

**Comment by hongyonghan** [comment]
docker run -d -p 1066:1066 -e TZ=Asia/Shanghai -e sender="byxxx@163.com" -e pwd="UxxxxWWN" -e receiver="41xxxxx@qq.com" -e adminpwd="123456" hanhongyong/ms365-e5-renew-x:arm64v8

**Comment by hongyonghan** [comment]
这个呢？

**Comment by a1564471347** [comment]
> 这个呢？

就这个可以用，其他命令安装后不显示端口所以打不开，这个命令我没有修改邮箱就默认，反正也不需要推送

**Comment by hongyonghan** [comment]
你的服务器是arm64v8的是嘛

**Comment by hongyonghan** [comment]
那个arm版本的我恢复到以前的那个版本了，你试试可以嘛？这个版本可能更小一点。
