### ISSUE TITLE
增加32位处理器arm v5的支持

### ISSUE THREAD

**Issue by xiaoweiXX** [hongyonghan/Docker_Microsoft365_E5_Renew_X#48]
我部署容器并运行的时候，出现了以下的报错：
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
be49221d0d88ba327756cee1f1ff66bab831997db41fa0d536f6633331d14806
我使用的是玩客云小主机，soc是晶晨s805，是一颗armv5的32位处理器。

**Comment by hongyonghan** [comment]
收到。会在下一个版本增加armv532的支持。

**Comment by xiaoweiXX** [comment]
> 收到。会在下一个版本增加armv532的支持。

弱弱的问一下，大概什么时候能更新。。。

**Comment by hongyonghan** [comment]
已经增加arm32v5的支持了

**Comment by xiaoweiXX** [comment]
> 已经增加arm32v5的支持了

非常尴尬，我又问了一遍AI，我使用的这颗soc实际上是arm v7架构的。试了几个镜像都不行，不是提示架构不对就是报错exec user process caused: exec format error。总之都无法运行。
