### ISSUE TITLE
邮箱通知乱码

### ISSUE THREAD

**Issue by meotao** [hongyonghan/Docker_Microsoft365_E5_Renew_X#49]
按照 **Email通知功能(推荐,20230402更新。)**方法进行部署，但收到的邮件全是乱码
![20230411010456](https://user-images.githubusercontent.com/7713597/230952802-6f19caea-b3a2-4498-aed5-85a5f2989eb3.png)

**Comment by zack-zzq** [comment]
这个是机器编码问题，我也遇到过。
我的环境是ubuntu22，中止原先的容器后安装language-pack-zh-hans包然后重建容器就能正常显示了。其他操作系统应该同理。

**Comment by yxd-python** [comment]
我是手机上看是乱码，电脑上正常，还有个问题，就是就算你没有添加帐号，他每天也会发送邮件说账号正常，这算bug吧

**Comment by hongyonghan** [comment]
最近事情很多，暂时不考虑更新以及修复bug，会在下一个版本统一修复。编码问题可以自己在服务器里面设置。
