### ISSUE TITLE
serverless部署

### ISSUE THREAD

**Issue by gd1214b** [hongyonghan/Docker_Microsoft365_E5_Renew_X#5]
1. 登陆Koybe平台：<https://koyeb.com/>
2. 创建一个新的应用:
![屏幕截图 2022-03-15 174653](https://user-images.githubusercontent.com/37929478/158351273-ebdf7843-9ecb-4203-bdd2-15f4b79932cd.png)
3.  输入docker 镜像地址：`docker.io/hanhongyong/ms365-e5-renew-x`
![image](https://user-images.githubusercontent.com/37929478/158351587-855d9ebf-4c47-4156-8591-2eaaf99fc957.png)
4. 修改端口为`1066`:
![image](https://user-images.githubusercontent.com/37929478/158352164-0a33d910-c005-4f13-8a0a-805a1c45671d.png)
5.创建应用：
![image](https://user-images.githubusercontent.com/37929478/158352317-ea08c3c1-cf54-4271-9c59-a9465d51fc25.png)
6.稍等几分钟即可完成部署，点击这里打开应用：
![image](https://user-images.githubusercontent.com/37929478/158352534-87a3a30b-4275-4d57-b87c-dded046a2a1d.png)
7. 输入默认密码`123456`完成登陆：
![image](https://user-images.githubusercontent.com/37929478/158352720-5b435753-2015-4a5a-918a-7284194943c9.png)

demo：<https://web-renew-gd1214b.koyeb.app/>

**Comment by hongyonghan** [comment]
您好！serverless相关部署方式已经放置在主页上了，谢谢您提供的相关的部署方式！

**Comment by foxdodo** [comment]
小白问下怎么改登录密码?

**Comment by tuthanika** [comment]
Can you help me how to change admin account password on koyeb? I used koyeb's Console with command vim Config.xml but it doesn't show up as your instructions.
