### ISSUE TITLE
账号跑成功了，但是时间没续上是怎么办？

### ISSUE THREAD

**Issue by xianweibo** [hongyonghan/Docker_Microsoft365_E5_Renew_X#51]
![1681381736695](https://user-images.githubusercontent.com/34569466/231732077-de7cb8a5-94e3-42fc-8995-c959abfa1596.png)

![1681381774362](https://user-images.githubusercontent.com/34569466/231732221-908dc19c-7865-4ff7-916e-de721349c008.png)

**Comment by yxd-python** [comment]
跑归跑，时间是微软给你续，一般都是剩余一个月之内的随机续

**Comment by hongyonghan** [comment]
续时间大约是一个月的时候开始续期，会发邮件通知。 @xianweibo
