### ISSUE TITLE
账号老是自动停止

### ISSUE THREAD

**Issue by tuutoo** [hongyonghan/Docker_Microsoft365_E5_Renew_X#55]
可能是我家网络不太稳定吧，能不能有个选项关闭自动停止。

因为我判断可能就是家里网络不太稳定。
老是自己停止我又要编辑一下保存。

**Comment by hongyonghan** [comment]
暂时不考虑关闭自动停止功能。这样账号的状态无法准确获得。给的建议如下，一是考虑入手一个国内的服务器（最好是国外的，最稳定）。二是对容器进行定时关闭和重启，国内网络主要是夜间时段不太稳定，可以避开这个时间段。
