### ISSUE TITLE
请问docker版如何映射需要跑的账号配置？

### ISSUE THREAD

**Issue by stefaneliu** [hongyonghan/Docker_Microsoft365_E5_Renew_X#6]
请问一下docker版本下，账号配置文件在什么地方？因为我每次重建容器后，原有的账号都消失了，都需要重新配置。我估计是因为账号配置没有映射出来的关系。但是我水平比较差，容器里没有找到相关文件，从而无法映射出来。
希望大佬能帮忙指点一下，感谢！

**Comment by hongyonghan** [comment]
您好！通过`docker exec -it [您的容器的ID] bash`进入容器，然后在当前目录下有个目录为appdata，下面是你的所有的账号的信息。如果需要，在映射的时候可以加上`-v 您的本地目录:/app/appdata`进行映射。

**Comment by stefaneliu** [comment]
非常感谢！
