### ISSUE TITLE
ARM版本的登录密码123456不对?

### ISSUE THREAD

**Issue by goooxyz** [hongyonghan/Docker_Microsoft365_E5_Renew_X#60]
ARM版本的登录密码123456不对?

**Comment by cuiren** [comment]
~~同问…之前3月下旬拉取的镜像没问题，昨天新拉取的镜像部署后密码就变了…可以在哪里查到吗？~~
解决了…看了下镜像里的Config.xml 密码写成了${adminpwd}  cp该文件到宿主机将密码字段改成合适的再cp回镜像，重启就可以了

**Comment by hongyonghan** [comment]
在部署的时候，看看使用最新的命令可以吗？`docker run -d -p 1066:1066 -e TZ=Asia/Shanghai -e sender="by123@163.com" -e pwd="UNxxxxxxxxN" -e receiver="4dddqqq9dd6@qq.com"  -e adminpwd="123456" hanhongyong/ms365-e5-renew-x::arm64v8`

**Comment by YuriSizuku** [comment]
> 在部署的时候，看看使用最新的命令可以吗？`docker run -d -p 1066:1066 -e TZ=Asia/Shanghai -e sender="by123@163.com" -e pwd="UNxxxxxxxxN" -e receiver="4dddqqq9dd6@qq.com" -e adminpwd="123456" hanhongyong/ms365-e5-renew-x::arm64v8`

arm版用这个命令行依旧不能登录

**Comment by foxdodo** [comment]
今天下载的镜像密码还是没改🤣新建的管理员密码`${adminpwd}`

**Comment by Georgebobby** [comment]
這個還是不行，去看了一下Deploy/Config.xml 看到密碼被寫死為123456，如果不能登入的人，可以用123456登入，再跑docker 命令時的-e 沒有作用.
