### ISSUE TITLE
错误：应用程序不存在此账户中

### ISSUE THREAD

**Issue by yltx** [hongyonghan/Docker_Microsoft365_E5_Renew_X#61]
![image.png](https://s2.loli.net/2023/04/26/lbhucJsOSRk21KW.png)

事实上我确实是用这个账号注册的应用程序啊……

**Comment by hongyonghan** [comment]
看看是不是权限没有打开，或者是不是没有登录调用？

**Comment by yltx** [comment]
> 看看是不是权限没有打开，或者是不是没有登录调用？

![image.png](https://s2.loli.net/2023/04/30/7cnZzqKbRJlivhA.png)应该没缺权限吧

**Comment by yltx** [comment]
> 看看是不是权限没有打开，或者是不是没有登录调用？

选的也是登录调用

**Comment by hongyonghan** [comment]
换个账户试试？重新注册一个子账号

**Comment by yltx** [comment]
> 换个账户试试？重新注册一个子账号

我用申请E5的账号和新建的账号都试了啊

**Comment by yltx** [comment]
问题解决，我把客户端id和密钥弄混了……
