### ISSUE TITLE
理应支持的处理器却无法运行

### ISSUE THREAD

**Issue by xiaoweiXX** [hongyonghan/Docker_Microsoft365_E5_Renew_X#64]
我收了一台二手的K40，使用的是高通骁龙870，架构是arm v8，是一个64位处理器。我特地为手机刷入支持docker的内核，也装入了docker支持，这块soc理应能够运行renew x，但是却显示不支持该架构。
![屏幕截图 2023-05-17 044501](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/92417243/19a67388-d723-4d71-9802-4797e9f377eb)

**Comment by hongyonghan** [comment]
我更新了一个通用版，可以去试试通用版
