### ISSUE TITLE
已暂停 (账户登录被双重验证阻止)

### ISSUE THREAD

**Issue by unixcs** [hongyonghan/Docker_Microsoft365_E5_Renew_X#65]
登录方式：登录调用权限配置

登录账号密码后，运行报错
![image](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/47837855/a6c6311a-5192-4c2a-b67c-cdacbff42df0)

**Comment by unixcs** [comment]
账号双重认证 未找到关闭按钮

**Comment by hongyonghan** [comment]
这个是关闭的链接啊。
https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview
