### ISSUE TITLE
email版问题

### ISSUE THREAD

**Issue by a1564471347** [hongyonghan/Docker_Microsoft365_E5_Renew_X#68]
隔一段时间就打不开网页，需要删除容器重新部署，进docker发现端口1066没有了

**Comment by hongyonghan** [comment]
是容器被关了吗？email版本是在第一版基础上加了邮件的功能，其他没有改变。感觉可能是服务器本身的问题

**Comment by a1564471347** [comment]
> 是容器被关了吗？email版本是在第一版基础上加了邮件的功能，其他没有改变。感觉可能是服务器本身的问题

早就没有问题了
