### ISSUE TITLE
为什么Docker镜像越来越大？

### ISSUE THREAD

**Issue by skyls03** [hongyonghan/Docker_Microsoft365_E5_Renew_X#7]
如图：
![image](https://user-images.githubusercontent.com/45219522/159958339-e7a14932-ad6e-4ca2-a28c-2cb9dc2f4f9a.png)

内存占用，有时也会跑到三百多M

**Comment by hongyonghan** [comment]
为了更方便使用，镜像加入了vim等软件。如果想要更小的版本可以使用`docker push hanhongyong/ms365-e5-renew-x:slim`来获得相对较小的版本。
