### ISSUE TITLE
可否麻烦增加linux/arm/v7的支持

### ISSUE THREAD

**Issue by zhuhonghao0323** [hongyonghan/Docker_Microsoft365_E5_Renew_X#70]
辛苦

**Comment by hongyonghan** [comment]
现在已经有arm64v7的版本了啊

**Comment by hongyonghan** [comment]
已经增加了通用版。欢迎进行测试，linux/arm/v7

**Comment by xiaoweiXX** [comment]
> 已经增加了通用版。欢迎进行测试，linux/arm/v7

具体的标签是哪个？我试了armv7提示不存在，arm是64位架构不行，general会提示 exec format error
