### ISSUE TITLE
可否部署在已有其它dock程序的vps中？

### ISSUE THREAD

**Issue by lesliehua** [hongyonghan/Docker_Microsoft365_E5_Renew_X#71]
你好，

原本部署renew的vps就要到期了，是否可以将其追加部署在我另一个已经部署过其它dock程序的vps中？例如用dock安装的宝塔面板+x-ui这俩。
感谢～

LEslie

**Comment by hongyonghan** [comment]
也可以尝试用免费的容器平台啊，这个也可以的

**Comment by lesliehua** [comment]
好的，非常感谢。
另外，使用宝塔面板里的dock也部署成功了
