### ISSUE TITLE
email通知不支持配置qq邮箱作为发送邮箱

### ISSUE THREAD

**Issue by OwnerCM** [hongyonghan/Docker_Microsoft365_E5_Renew_X#72]
email通知不支持配置qq邮箱作为发送邮箱
![image](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/22722811/b6539e03-c539-4f60-93cf-4cecdde558b8)
![image](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/22722811/e09d75a5-6385-494b-9358-a1db8573c816)

**Comment by hongyonghan** [comment]
是的，目前设置的是163邮箱。也推荐使用这个邮箱啊。

**Comment by StackExplode** [comment]
那是否支持自己的SMTP服务器呢？或者使用Linux自带的`mail`命令发送？
