### ISSUE TITLE
监视日志里有一项“团队合作.团队.列出你的团队”的API，每次都调用失败

### ISSUE THREAD

**Issue by ddclaus** [hongyonghan/Docker_Microsoft365_E5_Renew_X#79]
这个API不知道英文是什么，在微软后台里没找到类似的API项目。麻烦作者指点一下。
![屏幕截图 2023-12-09 123208](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/39852707/9d8f1d7a-3017-4b6a-8319-5f448abb1198)

**Comment by hongyonghan** [comment]
我看了一下我的啊，这个和服务器所在的位置有关系。国内可能有些服务器调用超时。我的是azure的服务器。目前全部都可以调用正常
