### ISSUE TITLE
我愣是进不去deploy改配置文件密码……

### ISSUE THREAD

**Issue by viyv** [hongyonghan/Docker_Microsoft365_E5_Renew_X#8]
我愣是进不去deploy改配置文件密码……

**Comment by hongyonghan** [comment]
是进不去容器吗？进入容器的命令是`docker exec -it  [你的容器id]   bash`，进入以后就是/app文件夹下，然后`cd Deploy/`进入即可。

**Comment by viyv** [comment]
你好，我访问到这个文件了，但是vim它，里面是空白的……请问我哪一步操作错误呢

**Comment by hongyonghan** [comment]
好的好的
