### ISSUE TITLE
有什么办法能让续期服务不走代理吗

### ISSUE THREAD

**Issue by laorentou666** [hongyonghan/Docker_Microsoft365_E5_Renew_X#82]
设备上使用了代理软件，导致续期时经常报错`The SSL connection could not be established`，在常见问题中找到了是代理软件的问题，但docker版内似乎没有不走代理的选项，有什么办法能让续期服务不走代理吗（或在代理软件内调整相关设置）?

![image](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/89732460/bda56014-36e9-410c-8893-ef6a439b5951)

**Comment by hongyonghan** [comment]
没有办法，开个国外服务器？
