### ISSUE TITLE
管理员密码显示错误

### ISSUE THREAD

**Issue by leonard4546** [hongyonghan/Docker_Microsoft365_E5_Renew_X#83]
我在arm服务器上运行

docker run -p 1066:1066 -e TZ=Asia/Shanghai --name ms365arm -e adminpwd="123456" hanhongyong/ms365-e5-renew-x:arm

但它显示我的密码错误

![image](https://github.com/hongyonghan/Docker_Microsoft365_E5_Renew_X/assets/61791543/2a5a9169-0fcb-48dc-a5c9-575aad266b48)

**Comment by jiaoting** [comment]
同样的问题

**Comment by LINKlang** [comment]
同样

**Comment by hongyonghan** [comment]
你好，hanhongyong/ms365-e5-renew-x:arm这个不支持命令里面设置密码啊，需要手动修改密码的

**Comment by jiaoting** [comment]
> 你好，hanhongyong/ms365-e5-renew-x:arm这个不支持命令里面设置密码啊，需要手动修改密码的

如何手动设置？

**Comment by hongyonghan** [comment]
我在主页上加上了，可以去看一下啊

**Comment by jiaoting** [comment]
![Uploading image.png…]()
我根据这个设置的，可是木有用哇

**Comment by hongyonghan** [comment]
docker run -d -p 1066:1066 -e TZ=Asia/Shanghai --name ms365  hanhongyong/ms365-e5-renew-x:arm
这个命令吗

**Comment by jiaoting** [comment]
docker run -d -p 1066:1066 --restart=always -e TZ=Asia/Shanghai -e --name ms365-e5-renew-x hanhongyong/ms365-e5-renew-x:latest

**Comment by hongyonghan** [comment]
修改密码的位置。密码的设置文件为容器中/app/Deploy目录下的Config.xml文件，修改内容为123456,将123456修改成自己的密码即可。修改后重启容器
