### ISSUE TITLE
版本和密码

### ISSUE THREAD

**Issue by gccola** [hongyonghan/Docker_Microsoft365_E5_Renew_X#84]
1、通用版本在arm64上无法运行；
2、ARM版本管理员密码123456错误

**Comment by tenshand** [comment]
123456

**Comment by hongyonghan** [comment]
好的，最近看一下啊

**Comment by hongyonghan** [comment]
ARM版本管理员密码123456错误, 这个进去修改一下密码看看呢？

**Comment by gccola** [comment]
> ARM版本管理员密码123456错误, 这个进去修改一下密码看看呢？

进文本修改就可以了，没仔细看帖子，抱歉！
PS.我把文本里面的那一堆复制出来直接登录再保存密码了，感谢回复！
